reveal:
  version:    3.3.0
  

markdown:    kramdown
highlighter: rouge
collections:
  presentations:
    permalink: /:path/
    output: true
  slides:

defaults:
  - scope:
      path: ""
      type: presentations
    values:
      layout: presentation
